apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app: assistente-juridico
  managed-by: kustomize

images:
  - name: assistente-juridico-p
    newTag: latest

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - PORT=3001

secretGenerator:
  - name: assistente-juridico-secrets
    literals:
      - app-env=production
    options:
      disableNameSuffixHash: true
