apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: assistente-juridico-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: assistente-juridico
  unhealthyPodEvictionPolicy: AlwaysAllow
