gitops:
  manifest_projects:
  - paths:
      glob: 'k8s/**/*.yaml'
    reconcile:
      mode: auto
      timeout: 3600s

ci_access:
  projects:
  - id: thiagobodevan-a11y/assistente-juridico-p

user_access:
  access_as:
    agent: {} # for free
    user: {} # for premium+
  projects:
  - id: thiagobodevan-a11y/assistente-juridico-p

observability:
  logging:
    level: debug
    grpc_level: warn
